apiVersion: apps/v1
kind: Deployment
metadata:
 name: node-web-app
spec:
 replicas: 2
 selector:
     matchLabels:
       app: node-web-app
 template:
   metadata:
     labels:
       app: node-web-app
   spec:     # pod spec                  
     containers:
     - name: node-web-app
       image: us.icr.io/cldstd40-ns/node-web-app:latest
       ports:
         - containerPort: 8080
       env:
         - name: APIKEY
           value: 5lXvuGrDTfDvctXExRCy1p1X79sUqX-g_x1OqKY0ZyMg
         - name: URL
           value: https://api.us-south.assistant.watson.cloud.ibm.com/instances/dbbebe9d-8612-4b33-ad46-25d90b5b3fd9
         - name: ASSISTANT_ID
           value: 4263f8ce-cf93-453c-818e-d6c9ab2cc855
       imagePullPolicy: Always



