apiVersion: apps/v1
kind: Deployment
metadata:
 name: node-web-app
spec:
 replicas: 2
 selector:
     matchLabels:
       app: node-web-app
 template:
   metadata:
     labels:
       app: node-web-app
   spec:     # pod spec                  
     containers:
     - name: node-web-app
       image: us.icr.io/cldstd40-ns/node-web-app:latest
       ports:
         - containerPort: 8080
       env:
         - name: APIKEY
           value: w9kKE7rI4Jj_sStPwsAwbKGEp_ResyAWZknES0Je7yfs
         - name: URL
           value: https://gateway-wdc.watsonplatform.net/assistant/api
         - name: ASSISTANT_ID
           value: 92994250-973c-462b-b084-32f1829cb4e7
       imagePullPolicy: Always